Repository Banana-Byte-Entertainment/Fish-n-Chimps, pull requests merged in 2024-12, with the labels that each got.

#50 Fixing boss logic
  Assets/Prefabs/HealthSys.prefab
  Assets/Prefabs/Tentacle.prefab
  Assets/Prefabs/quid.prefab
  Assets/Scenes/BossTestScene.unity
  Assets/Scenes/Level1.unity
  Assets/Scenes/SwimmingTestScene.unity
  Assets/Scripts/BossFightManager.cs
  Assets/Scripts/Fish/FishMovement.cs
  Assets/Scripts/HealthBar.cs
  Assets/Scripts/InventorySystem/InventoryManager.cs
  Assets/Scripts/PlayerBar.cs
  Assets/Scripts/PlayerBar.cs.meta
  Assets/Scripts/SquidAttack.cs
  Assets/Scripts/TentacleScroll.cs
Labels: bug

#56 Fixed issue with crafting menu not showing up
  Assets/Objects/CraftingRecipes/Halo.asset
  Assets/Objects/Items/Halo.asset
  Assets/Objects/Items/Halo.asset.meta
  Assets/Prefabs/CraftingSystem.prefab
  Assets/Prefabs/InventorySystem.prefab
  Assets/Scenes/Inventory&CraftingSystemDemo.unity
Labels: bug

#57 Transition into Boss Fight
  Assets/Scenes/Level1.unity
  Assets/Scripts/BossTransition.cs
Labels: new

#58 Boss HealthBar
  Assets/BossSlide.cs
  Assets/Scenes/BossTestScene.unity
  Assets/Scenes/Level1.unity
  Assets/Scripts/BossTransition.cs
  Assets/Scripts/Fish/FishMovement.cs
  Assets/Scripts/HealthBar.cs
Labels: bug, new

#61 Finished Boss Fight V1
  Assets/BossSlide.cs
  Assets/Prefabs/Tentacle.prefab
  Assets/Scenes/Level1.unity
  Assets/Scripts/BossFightManager.cs
  Assets/Scripts/BossTransition.cs
  Assets/Scripts/HealthBar.cs
  Assets/Scripts/QuidManager.cs
  Assets/Scripts/QuidManager.cs.meta
  Assets/Scripts/SquidAttack.cs
  Assets/Scripts/TentacleManager.cs
  Assets/Scripts/TentacleManager.cs.meta
  Assets/Scripts/TentacleScroll.cs
Labels: bug, new

#62 Player moves to new scene for boss fight
  Assets/Objects/CraftingRecipes/TestRecipes.meta
  Assets/Objects/CraftingRecipes/TestRecipes/Boats.asset
  Assets/Objects/CraftingRecipes/TestRecipes/ChestBoats.asset
  Assets/Objects/CraftingRecipes/TestRecipes/ChestBoats.asset.meta
  Assets/Objects/CraftingRecipes/TestRecipes/DiamondAxes.asset
  Assets/Objects/CraftingRecipes/TestRecipes/DiamondAxes.asset.meta
  Assets/Objects/CraftingRecipes/TestRecipes/DiamondBlocks.asset
  Assets/Objects/CraftingRecipes/TestRecipes/DiamondBlocks.asset.meta
  Assets/Objects/CraftingRecipes/TestRecipes/DiamondBoots.asset
  Assets/Objects/CraftingRecipes/TestRecipes/DiamondBoots.asset.meta
  Assets/Objects/CraftingRecipes/TestRecipes/DiamondChestplates.asset
  Assets/Objects/CraftingRecipes/TestRecipes/DiamondPickaxes.asset
  Assets/Objects/CraftingRecipes/TestRecipes/DiamondPickaxes.asset.meta
  Assets/Objects/CraftingRecipes/TestRecipes/DiamondSwords.asset
  Assets/Objects/CraftingRecipes/TestRecipes/DiamondSwords.asset.meta
  Assets/Objects/CraftingRecipes/TestRecipes/FenceGates.asset
  Assets/Objects/CraftingRecipes/TestRecipes/Furnaces.asset
  Assets/Objects/CraftingRecipes/TestRecipes/Furnaces.asset.meta
  Assets/Objects/CraftingRecipes/TestRecipes/Ladders.asset
  Assets/Objects/CraftingRecipes/TestRecipes/Ladders.asset.meta
  Assets/Objects/CraftingRecipes/TestRecipes/NetheriteChestplate.asset
  Assets/Objects/CraftingRecipes/TestRecipes/OakPlanks.asset
  Assets/Objects/CraftingRecipes/TestRecipes/OakPlanks.asset.meta
  Assets/Objects/CraftingRecipes/TestRecipes/Sticks.asset
  Assets/Objects/CraftingRecipes/TestRecipes/Sticks.asset.meta
  Assets/Prefabs/Managers.meta
  Assets/Prefabs/Managers/BossTransitionManager.prefab
  Assets/Prefabs/Managers/BossTransitionManager.prefab.meta
  Assets/Prefabs/Managers/CraftingSystem.prefab
  Assets/Prefabs/Managers/CraftingSystem.prefab.meta
  Assets/Prefabs/Managers/InventorySystem.prefab
  Assets/Prefabs/Managers/InventorySystem.prefab.meta
  Assets/Prefabs/Managers/PauseMenuManager.prefab
  Assets/Prefabs/Managers/PauseMenuManager.prefab.meta
  Assets/Prefabs/PlayerHealthBar.prefab
  Assets/Prefabs/PlayerHealthBar.prefab.meta
  Assets/Scenes/FromCopySceneDemo.unity
  Assets/Scenes/FromCopySceneDemo.unity.meta
  Assets/Scenes/Level1.unity
  Assets/Scenes/ToCopySceneDemo.unity
  Assets/Scenes/ToCopySceneDemo.unity.meta
  Assets/Scripts/BossTransition.cs
  Assets/Scripts/ChangeToBossScript.cs
  Assets/Scripts/ChangeToBossScript.cs.meta
  Assets/Scripts/TransitionManager.cs
  ProjectSettings/EditorBuildSettings.asset
Labels: new

#63 Put Boss Fight Into New Scene
  Assets/BossSlide.cs
  Assets/Scenes/ToCopySceneDemo.unity
  Assets/Scripts/SquidAttack.cs
  Assets/Scripts/TentacleScroll.cs
Labels: improvement

#65 Removed More Debug.Log()
  Assets/Scripts/Fish/FishMovement.cs
  Assets/Scripts/Fish/FishSpawner.cs
  Assets/Scripts/Player Movement/PlayerMovementAndOxygen.cs
Labels: improvement
