Repository Banana-Byte-Entertainment/Fish-n-Chimps, pull requests merged in 2025-02, with the labels that each got.

#78 Gorilla revival
  Assets/Backgrounds/Comic.jpg
  Assets/Backgrounds/Comic.jpg.meta
  Assets/Prefabs/FishPrefabs/BusFish.prefab
  Assets/Prefabs/Gorilla.prefab
  Assets/Prefabs/Gorilla.prefab.meta
  Assets/Scenes/Level1.unity
  Assets/Scenes/SampleLaunch.unity
  Assets/Scenes/TitleScreen.unity
  Assets/Scripts/MoveInvisibleBox.cs
  Assets/Scripts/MoveInvisibleBox.cs.meta
  Assets/Scripts/UI/MainTitle.cs
  Assets/Sprites/Arrow.png
  Assets/Sprites/Arrow.png.meta
  Assets/Sprites/Monkeys/Monkey3.png
  Assets/Sprites/Monkeys/Monkey3.png.meta
  Assets/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Bangers SDF.asset
Labels: new

#81 Fixed Wall Colliders, Optional Cutscene Text
  Assets/Objects/Items/Trinkets/BeanBuddy.asset.meta
  Assets/Objects/Items/Trinkets/NeedleGreenWhole.asset.meta
  Assets/Objects/Items/Weapons/Bananarang.asset.meta
  Assets/Objects/Items/Weapons/Halo.asset.meta
  Assets/Objects/Items/Weapons/JestersFeast.asset.meta
  Assets/Objects/Items/Weapons/NeedlePurpleWhole.asset.meta
  Assets/Scenes/BossLevel.unity
  Assets/Scenes/Level1.unity
  Assets/Scenes/TitleScreen.unity
  Assets/Scripts/Fish/FishMovement.cs
  Assets/Scripts/MoveInvisibleBox.cs
  Assets/Scripts/WeaponAttacks/WeaponManager.cs
  Assets/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Bangers SDF.asset
Labels: improvement

#90 Added Demonic Dolphin
  Assets/Prefabs/FishPrefabs/DemonicDolphin.prefab
  Assets/Prefabs/FishPrefabs/DemonicDolphin.prefab.meta
  Assets/Scenes/BossLevel.unity
  Assets/Scenes/Level1.unity
  Assets/Scenes/TitleScreen.unity
  Assets/Scripts/Boss/BossSlide.cs
  Assets/Sprites/FishSprites/demonic_dolphin.png
  Assets/Sprites/FishSprites/demonic_dolphin.png.meta
Labels: bug, new, improvement

#92 Inventory and transition bug fixes
  .gitignore
  Assets/Prefabs/Managers/PlayerHealthManager.prefab
  Assets/Prefabs/PlayerHealthBar.prefab
  Assets/Scenes/TitleScreen.unity
  Assets/Scripts/CraftingSystem/CraftingKeyHandler.cs
  Assets/Scripts/InventorySystem/InventoryKeyHandler.cs
  Assets/Scripts/InventorySystem/InventoryManager.cs
  Assets/Scripts/TransitionManager.cs
  Assets/Scripts/UI/OxygenBar.cs
  Assets/Scripts/UI/PauseMenuManager.cs
  Assets/TextMesh Pro/Resources/TMP Settings.asset
  ProjectSettings/EditorBuildSettings.asset
Labels: bug

#93 Rewrote transition manager
  Assets/Prefabs/Managers/BossTransitionManager.prefab
  Assets/Scenes/TransitionScene.unity
  Assets/Scripts/Boss/BossTransition.cs
  Assets/Scripts/InventorySystem/ItemContainer.cs
  Assets/Scripts/InventorySystem/ItemContainer.cs.meta
  Assets/Scripts/TransitionManager.cs
  Assets/Scripts/UI/PauseMenuManager.cs
  ProjectSettings/TimelineSettings.asset
Labels: new, improvement

#94 Update PauseMenuManager.cs
  Assets/Scripts/UI/PauseMenuManager.cs
Labels: bug
