Repository Banana-Byte-Entertainment/Fish-n-Chimps, pull requests merged in 2025-07, with the labels that each got.

#138 Health fixes & adding sea goat
  Assets/Prefabs/FishPrefabs/AngelFish.prefab
  Assets/Prefabs/FishPrefabs/BeanFish.prefab
  Assets/Prefabs/FishPrefabs/BusFish.prefab
  Assets/Prefabs/FishPrefabs/CatFish.prefab
  Assets/Prefabs/FishPrefabs/ClownFish.prefab
  Assets/Prefabs/FishPrefabs/DemonicDolphin.prefab
  Assets/Prefabs/FishPrefabs/Jellyfish1.prefab
  Assets/Prefabs/FishPrefabs/Jellyfish2.prefab
  Assets/Prefabs/FishPrefabs/NeedleFish1.prefab
  Assets/Prefabs/FishPrefabs/NeedleFish1.prefab.meta
  Assets/Prefabs/FishPrefabs/NeedleFish2.prefab
  Assets/Prefabs/FishPrefabs/NeedleFish2.prefab.meta
  Assets/Prefabs/FishPrefabs/StonedFish.prefab
  Assets/Prefabs/Gorilla.prefab
  Assets/Prefabs/bubbleButEVIL Variant.prefab
  Assets/Scenes/BossLevelVodyanoy.unity
  Assets/Scenes/Grungus.unity
  Assets/Scenes/Level2.unity
  Assets/Scripts/Boss1/BossTransition.cs
  Assets/Scripts/Boss2/BossMovement.cs
  Assets/Scripts/Bosses/General/Bubble.cs
  Assets/Scripts/Bosses/SeaGoat/SeaGoatManager.cs
  Assets/Scripts/Grungus/Grungus.cs
Labels: bug

#142 Removed Debug Logs
  Assets/Scripts/Boss1/BossFightManager.cs
  Assets/Scripts/Boss1/BossWeird.cs
  Assets/Scripts/Boss2/BossMovement.cs
  Assets/Scripts/General/ItemDropper.cs
  Assets/Scripts/Player/PlayerLaunch.cs
Labels: improvement

#144 Fixing issues & credits scene
  Assets/Objects/Minigame/Cooking/Ingredients/Processed Ingredients/BoiledPotato.asset
  Assets/Prefabs/EvilBubble.prefab
  Assets/Prefabs/EvilBubble.prefab.meta
  Assets/Prefabs/MainTitle.prefab
  Assets/Prefabs/Squid.prefab
  Assets/Prefabs/Squid.prefab.meta
  Assets/Prefabs/Tentacle.prefab
  Assets/Prefabs/Tentacle.prefab.meta
  Assets/Prefabs/bubble.prefab
  Assets/Prefabs/playerLaunch.prefab
  Assets/Scenes/Bosses/KrakenBoss.unity
  Assets/Scenes/Bosses/SeaGoatBoss.unity
  Assets/Scenes/Credits.unity
  Assets/Scenes/Credits.unity.meta
  Assets/Scenes/Levels.meta
  Assets/Scenes/Levels/Level1.unity
  Assets/Scenes/Levels/Level1.unity.meta
  Assets/Scenes/Minigames.meta
  Assets/Scenes/Minigames/CookingMinigame.unity
  Assets/Scenes/Minigames/CookingMinigame.unity.meta
  Assets/Scenes/TitleScreen.unity
  Assets/Scenes/WinGame.unity
  Assets/Scenes/WinGame.unity.meta
  Assets/Scripts/Boss1/BossFightManager.cs
  Assets/Scripts/Boss1/BossSlide.cs
  Assets/Scripts/Boss1/SquidAttack.cs
  Assets/Scripts/Boss1/SquidManager.cs
  Assets/Scripts/Boss1/SquidManager.cs.meta
  Assets/Scripts/Boss1/TentacleManager.cs
  Assets/Scripts/Boss1/TentacleScroll.cs
  Assets/Scripts/Bosses/General/Bubble.cs
  Assets/Scripts/General/CreditsScroller.cs
  Assets/Scripts/General/CreditsScroller.cs.meta
  Assets/Scripts/General/MoveInvisibleBox.cs
  Assets/Scripts/General/WinGame.cs
  Assets/Scripts/Minigame/Cooking/Managers/CookingMinigameManager.cs
  Assets/Scripts/Minigame/Cooking/ScriptableObjects/CookingIngredient.cs
  Assets/Scripts/UI/HealthBars/HealthBar.cs
  Assets/Scripts/UI/MainMenuManager.cs
  Assets/Scripts/UI/MainMenuManager.cs.meta
  Assets/Scripts/UI/MainTitle.cs
  Assets/Scripts/UI/PauseMenuManager.cs
  Assets/Sounds/BossMusic.meta
  Assets/Sounds/BossMusic/SeaGoatMusic.mp3
  Assets/Sounds/BossMusic/SeaGoatMusic.mp3.meta
  Assets/Sprites/Minigame/Cooking/Sunny-SideUpEgg.png
  Assets/Sprites/Minigame/Cooking/Sunny-SideUpEgg.png.meta
  Assets/Sprites/UI/Credits.png
  Assets/Sprites/UI/Credits.png.meta
  Assets/Sprites/UI/Exit.png
  Assets/Sprites/UI/Exit.png.meta
  Assets/Sprites/UI/Minigame.png
  Assets/Sprites/UI/Minigame.png.meta
  Assets/URPSettings/New Universal Render Pipeline Asset.asset
  ProjectSettings/EditorBuildSettings.asset
Labels: new, improvement

#143 Adjusted style elements
  Assets/Scenes/BossLevelVodyanoy.unity
  Assets/Scenes/Grungus.unity
  Assets/Scenes/Level2.unity
  Assets/Sounds/frog.mp3
  Assets/Sounds/frog.mp3.meta
Labels: improvement
