Repository Banana-Byte-Entertainment/Fish-n-Chimps, pull requests merged in 2025-03, with the labels that each got.

#95 Win screen
  Assets/Scenes/WinLvl1.unity
  Assets/Scenes/WinLvl1.unity.meta
  Assets/Scripts/Boss/BossSlide.cs
  Assets/Scripts/Lvl1Win.cs
  Assets/Scripts/Lvl1Win.cs.meta
  Assets/Sprites/gorilla_the_grilla.png
  Assets/Sprites/gorilla_the_grilla.png.meta
  Assets/Sprites/kraken_dish.png
  Assets/Sprites/kraken_dish.png.meta
  ProjectSettings/EditorBuildSettings.asset
Labels: new, improvement

#98 Score counter & added trinket
  Assets/Objects/Items/Bean.asset
  Assets/Objects/Items/Lasagna.asset
  Assets/Objects/Items/Trinkets/BeanBuddy.asset
  Assets/Objects/Items/Trinkets/HaloWhole.asset
  Assets/Objects/Items/Trinkets/HaloWhole.asset.meta
  Assets/Objects/Items/Trinkets/NeedleGreenWhole.asset
  Assets/Objects/Items/Weapons/NeedlePurpleWhole.asset
  Assets/Prefabs/Player.prefab
  Assets/Scenes/Level1.unity
  Assets/Scripts/Boss/BossSlide.cs
  Assets/Scripts/Fish/FishSpawner.cs
  Assets/Scripts/General.meta
  Assets/Scripts/InventorySystem/InventoryManager.cs
  Assets/Scripts/InventorySystem/Item.cs
  Assets/Scripts/PlayerScore.cs
  Assets/Scripts/PlayerScore.cs.meta
  Assets/Scripts/UI/HealthBars/BossHealthBar.cs
  Assets/Scripts/UI/HealthBars/EnemyHealthBar.cs
  Assets/Scripts/UI/HealthBars/HealthBar.cs
  Assets/Scripts/UI/HealthBars/PlayerHealthBar.cs
  Assets/Scripts/UI/OxygenBar.cs
Labels: bug, new

#102 Changed Tentacles
  Assets/Animations/TentWoble.anim
  Assets/Animations/TentWoble.anim.meta
  Assets/Animations/Tentacle1.controller
  Assets/Animations/Tentacle1.controller.meta
  Assets/Prefabs/Tentacle1.prefab
  Assets/Prefabs/Tentacle1.prefab.meta
  Assets/Scenes/BossLevel.unity
  Assets/Scenes/Level1New.unity
  Assets/Scripts/Boss/TentacleScroll.cs
  Assets/Sprites/BossLevel/Tentacle1.png
  Assets/Sprites/BossLevel/Tentacle1.png.meta
  Assets/Sprites/BossLevel/Tentacle2.png
  Assets/Sprites/BossLevel/Tentacle2.png.meta
  Assets/Sprites/BossLevel/Tentacle3.png
  Assets/Sprites/BossLevel/Tentacle3.png.meta
Labels: improvement
