Repository Banana-Byte-Entertainment/Fish-n-Chimps, pull requests merged in 2025-01, with the labels that each got.

#66 Oxygen bar fixes
  Assets/Prefabs/WeaponTarget.prefab
  Assets/Prefabs/WeaponTarget.prefab.meta
  Assets/Scenes/FromCopySceneDemo.unity
  Assets/Scenes/Level1.unity
  Assets/Scenes/ToCopySceneDemo.unity
  Assets/Scripts/BossTransition.cs
  Assets/Scripts/Player Movement/PlayerMovementAndOxygen.cs
Labels: bug, improvement

#67 Fixed Brackets
  Assets/Scripts/BossTransition.cs
  Assets/Scripts/ChangeToBossScript.cs
  Assets/Scripts/Fish/FishMovement.cs
  Assets/Scripts/Fish/FishSpawner.cs
  Assets/Scripts/InventorySystem/ArmourSlotHolder.cs
  Assets/Scripts/InventorySystem/InventoryBackgroundDropItem.cs
  Assets/Scripts/InventorySystem/InventoryItem.cs
  Assets/Scripts/InventorySystem/InventoryManager.cs
  Assets/Scripts/InventorySystem/InventorySlotHolder.cs
  Assets/Scripts/InventorySystem/Item.cs
  Assets/Scripts/Player Movement/PlayerMovementAndOxygen.cs
  Assets/Scripts/TransitionManager.cs
  Assets/Scripts/UI/MainTitle.cs
  Assets/Scripts/UI/PauseMenuManager.cs
Labels: improvement

#68 Created game over screen
  Assets/Scenes/GameOver.unity
  Assets/Scenes/GameOver.unity.meta
  Assets/Scripts/HealthBar.cs
  Assets/Sprites/GameOver.png
  Assets/Sprites/GameOver.png.meta
  ProjectSettings/EditorBuildSettings.asset
Labels: new

#69 Fixed issue when game over appeared if a fish died
  Assets/BossSlide.cs
  Assets/Scripts/HealthBar.cs
  Assets/Scripts/PlayerBar.cs
Labels: bug

#72 Armour and trinket slots
  Assets/BossSlide.cs
  Assets/Objects/CraftingRecipes/BeanBuddy.asset
  Assets/Objects/CraftingRecipes/BeanBuddy.asset.meta
  Assets/Objects/Items/Bean.asset
  Assets/Objects/Items/Equipables/BeanBuddy.asset
  Assets/Prefabs/FishPrefabs/AngelFish.prefab
  Assets/Prefabs/FishPrefabs/BeanFish.prefab
  Assets/Prefabs/FishPrefabs/BusFish.prefab
  Assets/Prefabs/FishPrefabs/CatFish.prefab
  Assets/Prefabs/FishPrefabs/ClownFish.prefab
  Assets/Prefabs/FishPrefabs/NeedleFish.prefab
  Assets/Prefabs/FishPrefabs/SillyNeedleFish.prefab
  Assets/Prefabs/Inventory/TrinketSlot.prefab
  Assets/Prefabs/ItemTooltip.prefab
  Assets/Prefabs/Managers/BossTransitionManager.prefab
  Assets/Prefabs/Managers/EnemyHealthManager.prefab
  Assets/Prefabs/Managers/EnemyHealthManager.prefab.meta
  Assets/Prefabs/Managers/InventorySystem.prefab
  Assets/Prefabs/Managers/PlayerHealthManager.prefab
  Assets/Prefabs/Managers/PlayerHealthManager.prefab.meta
  Assets/Prefabs/PlayerHealthBar.prefab
  Assets/Scenes/BossLevel.unity
  Assets/Scenes/BossLevel.unity.meta
  Assets/Scenes/Inventory&CraftingSystemDemo.unity
  Assets/Scenes/Level1.unity
  Assets/Scripts/Boss.meta
  Assets/Scripts/Boss/BossFightManager.cs
  Assets/Scripts/Boss/BossFightManager.cs.meta
  Assets/Scripts/Boss/BossTransition.cs
  Assets/Scripts/Boss/BossTransition.cs.meta
  Assets/Scripts/Boss/QuidManager.cs
  Assets/Scripts/Boss/QuidManager.cs.meta
  Assets/Scripts/Boss/SquidAttack.cs
  Assets/Scripts/Boss/SquidAttack.cs.meta
  Assets/Scripts/Boss/TentacleManager.cs
  Assets/Scripts/Boss/TentacleManager.cs.meta
  Assets/Scripts/Boss/TentacleScroll.cs
  Assets/Scripts/Boss/TentacleScroll.cs.meta
  Assets/Scripts/ChangeToBossScript.cs
  Assets/Scripts/Fish/FishMovement.cs
  Assets/Scripts/InventorySystem/ArmourSlotHolder.cs
  Assets/Scripts/InventorySystem/BackgroundDropItem.cs
  Assets/Scripts/InventorySystem/BackgroundDropItem.cs.meta
  Assets/Scripts/InventorySystem/InventoryManager.cs
  Assets/Scripts/InventorySystem/SlotHolders.meta
  Assets/Scripts/InventorySystem/SlotHolders/ArmourSlotHolder.cs
  Assets/Scripts/InventorySystem/SlotHolders/ArmourSlotHolder.cs.meta
  Assets/Scripts/InventorySystem/SlotHolders/InventorySlotHolder.cs
  Assets/Scripts/InventorySystem/SlotHolders/InventorySlotHolder.cs.meta
  Assets/Scripts/InventorySystem/SlotHolders/SlotHolder.cs
  Assets/Scripts/InventorySystem/SlotHolders/SlotHolder.cs.meta
  Assets/Scripts/InventorySystem/SlotHolders/TrinketSlotHolder.cs
  Assets/Scripts/InventorySystem/SlotHolders/TrinketSlotHolder.cs.meta
  Assets/Scripts/UI/HealthBars.meta
  Assets/Scripts/UI/HealthBars/HealthBar.cs
  Assets/Scripts/UI/HealthBars/HealthBar.cs.meta
  Assets/Scripts/UI/HealthBars/PlayerHealthBar.cs
  Assets/Scripts/UI/HealthBars/PlayerHealthBar.cs.meta
  ProjectSettings/EditorBuildSettings.asset
Labels: bug, new, improvement

#75 Updated project settings
  ProjectSettings/AudioManager.asset
  ProjectSettings/ProjectSettings.asset
  ProjectSettings/QualitySettings.asset
Labels: improvement

#73 Added Replay button
  Assets/Scenes/GameOver.unity
  Assets/Scripts/ChangeScene.cs
  Assets/Scripts/ChangeScene.cs.meta
  Assets/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Bangers SDF.asset
  Assets/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Electronic Highway Sign SDF.asset
Labels: new
